SmartSpot:
  required:
    - id
    - type
    - announcedUrl
    - signalStrength
    - bluetoothChannel
    - announcementPeriod
    - availability
  allOf:
    - $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/Common
  type: object
  description: |
    Smart Spots are devices which provide the technology which allows users to get
    access to smart points of interaction so that they can obtain extra information
    (infotainment, etc.), provide suggestions (suggestions mailbox, etc.) or
    generate new content (co-creation, etc.). The data model contains resources to
    configure the interaction service such as the broadcasted URL (typically
    shortened), the period between broadcasts, the availability of the service,
    transmission power depending on the area to be covered, etc.
  properties:
    alternateName:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/schema.org.yaml#/alternateName
    announcedUrl:
      x-ngsi:
        type: Property
        model: 'https://schema.org/URL'
      type: string
      description: URL broadcasted by the device
      format: uri
    announcementPeriod:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Integer'
      type: integer
      description: Period between announcements in milliseconds
      format: int32
    availability:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: >-
        Specifies the time intervals in which this interactive service is
        available, but this is a general information while Smart Spots have
        their own real availability in order to allow advanced configurations
    bluetoothChannel:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: Bluetooth channels where to transmit the announcement
    coverageRadius:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Integer'
      type: integer
      description: Radius of the spot coverage area in meters
      format: int32
    dataProvider:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/fiware-terms.yaml#/dataProvider
    description:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/description
    name:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/name
    owner:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/fiware-terms.yaml#/owner
    signalStrength:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: Signal strength to adjust the announcement range
    source:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/fiware-terms.yaml#/source
